[2025-10-09T06:05:14.823+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inventory_analytics_pipeline.generate_inventory_report scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T06:05:15.022+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inventory_analytics_pipeline.generate_inventory_report scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T06:05:15.036+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-09T06:05:15.287+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_inventory_report> on 2025-10-08 00:00:00+00:00
[2025-10-09T06:05:15.363+0000] {standard_task_runner.py:60} INFO - Started process 445 to run task
[2025-10-09T06:05:15.461+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inventory_analytics_pipeline', 'generate_inventory_report', 'scheduled__2025-10-08T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/inventory_analytics_pipeline.py', '--cfg-path', '/tmp/tmp58dmovd2']
[2025-10-09T06:05:15.477+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask generate_inventory_report
[2025-10-09T06:05:15.679+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-09T06:05:16.355+0000] {task_command.py:423} INFO - Running <TaskInstance: inventory_analytics_pipeline.generate_inventory_report scheduled__2025-10-08T00:00:00+00:00 [running]> on host ea4788e59d79
[2025-10-09T06:05:17.027+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inventory_analytics_pipeline' AIRFLOW_CTX_TASK_ID='generate_inventory_report' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-08T00:00:00+00:00'
[2025-10-09T06:05:17.213+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-10-09T06:05:17.572+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/inventory_analytics_pipeline.py:50 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-10-09T06:05:18.051+0000] {logging_mixin.py:188} INFO - âœ… Inventory report saved to CSV
[2025-10-09T06:05:18.296+0000] {logging_mixin.py:188} INFO -    id product_name  quantity    warehouse
0  13       Laptop        10  Warehouse A
1  14        Mouse        50  Warehouse B
2  15     Keyboard        30  Warehouse A
3  16      Monitor        15  Warehouse B
[2025-10-09T06:05:18.299+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-09T06:05:18.566+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=inventory_analytics_pipeline, task_id=generate_inventory_report, execution_date=20251008T000000, start_date=20251009T060514, end_date=20251009T060518
[2025-10-09T06:05:18.927+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-09T06:05:19.218+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
