[2025-10-07T05:52:13.054+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: inventory_analytics_pipeline.generate_inventory_report scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-07T05:52:13.193+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: inventory_analytics_pipeline.generate_inventory_report scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-07T05:52:13.215+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-07T05:52:13.529+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): generate_inventory_report> on 2025-10-06 00:00:00+00:00
[2025-10-07T05:52:13.659+0000] {standard_task_runner.py:60} INFO - Started process 3962 to run task
[2025-10-07T05:52:13.697+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'inventory_analytics_pipeline', 'generate_inventory_report', 'scheduled__2025-10-06T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/inventory_analytics_pipeline.py', '--cfg-path', '/tmp/tmp2pj87wmm']
[2025-10-07T05:52:13.753+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask generate_inventory_report
[2025-10-07T05:52:14.047+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-07T05:52:14.758+0000] {task_command.py:423} INFO - Running <TaskInstance: inventory_analytics_pipeline.generate_inventory_report scheduled__2025-10-06T00:00:00+00:00 [running]> on host ea4788e59d79
[2025-10-07T05:52:16.269+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='inventory_analytics_pipeline' AIRFLOW_CTX_TASK_ID='generate_inventory_report' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-06T00:00:00+00:00'
[2025-10-07T05:52:16.592+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-10-07T05:52:16.803+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/inventory_analytics_pipeline.py:50 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-10-07T05:52:17.122+0000] {logging_mixin.py:188} INFO - âœ… Inventory report saved to CSV
[2025-10-07T05:52:17.356+0000] {logging_mixin.py:188} INFO -    id product_name  quantity    warehouse
0   9       Laptop        10  Warehouse A
1  10        Mouse        50  Warehouse B
2  11     Keyboard        30  Warehouse A
3  12      Monitor        15  Warehouse B
[2025-10-07T05:52:17.405+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-10-07T05:52:17.690+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=inventory_analytics_pipeline, task_id=generate_inventory_report, execution_date=20251006T000000, start_date=20251007T055213, end_date=20251007T055217
[2025-10-07T05:52:18.252+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-10-07T05:52:18.852+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
